fpath=(/usr/local/share/zsh/site-functions $fpath)
dotfiles="/Users/sth/.dotfiles"

export PATH="./.bin:/usr/local/bin:/usr/local/share/npm/bin:/opt/chgems/bin:$PATH"

if [[ -d $dotfiles/zsh/conf.d ]]; then
  for conf in $dotfiles/zsh/conf.d/*.zsh; do
    source $conf
  done
fi
