# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# this will change depending on the bootstrap.sh exec
export dotfiles="__DOTFILES__"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="terminalparty"

plugins=(git osx)

# import language
source "/Users/sth/Development/dotfiles/language.zsh"

# import exports
source "/Users/sth/Development/dotfiles/exports.zsh"

# import aliases
source "/Users/sth/Development/dotfiles/aliases.zsh"

# import proxies
source "/Users/sth/Development/dotfiles/proxies.zsh"

source $ZSH/oh-my-zsh.sh

# rbenv & rbfu
eval "$(rbenv init -)"
eval "$(rbfu --init)"

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin